[package]
name = "gruthingy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayfire = "3.8.0"
ciborium = "0.2.1"
fastrand = "1.9.0"
nalgebra = "0.32.3"
serde = "1.0.171"

[profile.release]
panic = "abort"

[profile.release-debug]
inherits = "release"
debug = true
